### ISSUE TITLE
add universal nav bar

### ISSUE THREAD

**Issue by JoeDailey** [KappaEtaKappa/khk-alumni-db#2]
its like 7 lines across 2 files. check alumni-db for an example ctrl-f navbar. I suggest doing this on the server unless you want to clone khk-ssa and have it running side by side. The issue is that ssa is the only service that can offer up cookies. if you do it locally you'll have to comment out the 'domain:do.khk.org' on khk-ssa/home.js otherwise the cooke wont work.
Ask me for server access prefered.

**Comment by JoeDailey** [comment]
im dumb. dont do this.

**Comment by JoeDailey** [comment]
this is our only public service. we dont need it.

**Comment by JoeDailey** [comment]
fuck this also the wrong project. thought it was agendas. dont issue and drink boys and girls.

**Comment by maggiewhite** [comment]
lol ok sg. My parents are here this weekend, but I'll be working on agendas Monday night.
